# DISPLAY
#
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
GAME_NAME = 'Isometric Thing'
BACKGROUND_COLOR_NAME = 'black'

# FILE PATH
#
GRAPHICS_EXTENSION = '.png'
GRAPHICS_FOLDER = './graphics/'
GRAPHICS_TERRAIN_FOLDER = GRAPHICS_FOLDER + 'terrain/'
MAPS_EXTENSION = '.csv'
MAPS_FOLDER = './maps/'

# SPRITE INFO
#
SPRITE_SIZE = 32
MAP_X_OFFSET = SPRITE_SIZE // 2
MAP_Y_OFFSET = SPRITE_SIZE // 4

# TILE TYPES
#
TILE_TERRAIN = 'terrain'
TILE_TYPES = [TILE_TERRAIN]

# ERROR MESSAGES
#
UNKNOWN_TILE_TYPE = 'Requested Tile_Type for TileSet is unknown'
