# DISPLAY
#
import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
GAME_NAME = 'Isometric Thing'
BACKGROUND_COLOR_NAME = 'aquamarine3'

# FILE PATH
#
GRAPHICS_EXTENSION = '.png'
GRAPHICS_FOLDER = './graphics/'
GRAPHICS_TERRAIN_FOLDER = GRAPHICS_FOLDER + 'terrain/'
MAPS_EXTENSION = '.csv'
MAPS_FOLDER = './maps/'

# KEYBOARD INPUT
#
KEY_PRESSED_COOLDOWN = 100
KEY_DL = pygame.K_q
KEY_DR = pygame.K_s
KEY_UR = pygame.K_z
KEY_UL = pygame.K_a
KEY_CAMERA_CLOCKWISE = pygame.K_r
KEY_CAMERA_COUNTERCLOCKWISE = pygame.K_t
KEY_QUIT = pygame.K_ESCAPE

# SPRITE INFO
#
CAMERA_NORTH = 'north'
CAMERA_WEST = 'west'
CAMERA_EAST = 'east'
CAMERA_SOUTH = 'south'
CAMERA_ORIENTATIONS = [CAMERA_NORTH, CAMERA_WEST, CAMERA_SOUTH, CAMERA_EAST]
SPRITE_SIZE = 64
MAP_WIDTH = 16
MAP_LENGTH = 16
MAP_X_OFFSET = SPRITE_SIZE // 2
MAP_Y_OFFSET = SPRITE_SIZE // 4
CHARACTER_X_CENTER_OFFSET = 0
CHARACTER_Y_CENTER_OFFSET = -8
CHARACTER_STAIRS_Y_OFFSET = SPRITE_SIZE // 4
TILE0_X = (SCREEN_WIDTH - SPRITE_SIZE) // 2
TILE0_Y = SPRITE_SIZE
TILE_X_OFFSET = SPRITE_SIZE // 2
TILE_Y_OFFSET = SPRITE_SIZE // 4

# TILE TYPES
#
TILE_TERRAIN = 'terrain'
TILE_CHARACTER = 'character'
TILE_TYPES = [TILE_TERRAIN, TILE_CHARACTER]
TILE_STAIRS_SLOPES = [4, 5, 6, 7, 8, 9, 10, 11]

# CHARACTERS
#
CHARACTER_TEST = 'test'
CHARACTER_TYPES = [CHARACTER_TEST]
CHARACTER_SW = CAMERA_SOUTH + CAMERA_WEST
CHARACTER_SE = CAMERA_SOUTH + CAMERA_EAST
CHARACTER_NE = CAMERA_NORTH + CAMERA_EAST
CHARACTER_NW = CAMERA_NORTH + CAMERA_WEST
CHARACTER_ORIENTATIONS = [CHARACTER_SW, CHARACTER_SE, CHARACTER_NE, CHARACTER_NW]
MV_DL = 'DL'
MV_DR = 'DR'
MV_UR = 'UR'
MV_UL = 'UL'
MV_DIRECTIONS = [MV_DL, MV_DR, MV_UR, MV_UL]
MV_OFFSET_DICT = {
    MV_DL: {
        CAMERA_NORTH: (0, 1),
        CAMERA_WEST: (1, 0),
        CAMERA_SOUTH: (0, -1),
        CAMERA_EAST: (-1, 0)
    },
    MV_DR: {
        CAMERA_NORTH: (1, 0),
        CAMERA_WEST: (0, -1),
        CAMERA_SOUTH: (-1, 0),
        CAMERA_EAST: (0, 1)
    },
    MV_UR: {
        CAMERA_NORTH: (0, -1),
        CAMERA_WEST: (-1, 0),
        CAMERA_SOUTH: (0, 1),
        CAMERA_EAST: (1, 0)
    },
    MV_UL: {
        CAMERA_NORTH: (-1, 0),
        CAMERA_WEST: (0, 1),
        CAMERA_SOUTH: (1, 0),
        CAMERA_EAST: (0, -1)
    }
}
MV_CHAR_ORIENTATION_DICT = {
    MV_DL: {
        CAMERA_NORTH: CHARACTER_SW,
        CAMERA_WEST: CHARACTER_SE,
        CAMERA_SOUTH: CHARACTER_NE,
        CAMERA_EAST: CHARACTER_NW
    },
    MV_DR: {
        CAMERA_NORTH: CHARACTER_SE,
        CAMERA_WEST: CHARACTER_NE,
        CAMERA_SOUTH: CHARACTER_NW,
        CAMERA_EAST: CHARACTER_SW
    },
    MV_UR: {
        CAMERA_NORTH: CHARACTER_NE,
        CAMERA_WEST: CHARACTER_NW,
        CAMERA_SOUTH: CHARACTER_SW,
        CAMERA_EAST: CHARACTER_SE
    },
    MV_UL: {
        CAMERA_NORTH: CHARACTER_NW,
        CAMERA_WEST: CHARACTER_SW,
        CAMERA_SOUTH: CHARACTER_SE,
        CAMERA_EAST: CHARACTER_NE
    }
}
# Test Character
CTEST_IDLE_FRAMES = 1
CTEST_IDLE_SW_SPRITE_ID = 0
CTEST_IDLE_SE_SPRITE_ID = 10
CTEST_IDLE_NE_SPRITE_ID = 20
CTEST_IDLE_NW_SPRITE_ID = 30

# ERROR MESSAGES
#
UNKNOWN_TILE_TYPE = 'Requested Tile_Type for TileSet is unknown'
UNKNOWN_CHARACTER_TYPE = 'Requested Character_Type for TileSet is unknown'
UNKNOWN_CAMERA_ORIENTATION = f'Unknown Camera Orientation, assuming {CAMERA_NORTH}'
UNKNOWN_MOVE_DIRECTION = 'Requested Move_Direction is unknown'
INCORRECT_COORD_FORMAT = 'Incorrect coord format. Expected : (x, y, z)'
NOT_IMPLEMENTED_MOVE_DIRECTION = 'Requested Move_Direction is not implemented'
NOT_IMPLEMENTED_MOVE_ORIENTATION = 'Requestions Char_Orientation is not implemented'
