# DISPLAY
#
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
GAME_NAME = 'Isometric Thing'
BACKGROUND_COLOR_NAME = 'black'

# FILE PATH
#
GRAPHICS_EXTENSION = '.png'
GRAPHICS_FOLDER = './graphics/'
GRAPHICS_TERRAIN_FOLDER = GRAPHICS_FOLDER + 'terrain/'
MAPS_EXTENSION = '.csv'
MAPS_FOLDER = './maps/'

# SPRITE INFO
#
CAMERA_NORTH = 'north'
CAMERA_WEST = 'west'
CAMERA_EAST = 'east'
CAMERA_SOUTH = 'south'
CAMERA_ORIENTATIONS = [CAMERA_NORTH, CAMERA_WEST, CAMERA_SOUTH, CAMERA_EAST]
SPRITE_SIZE = 64
MAP_X_OFFSET = SPRITE_SIZE // 2
MAP_Y_OFFSET = SPRITE_SIZE // 4
CHARACTER_X_CENTER_OFFSET = 0
CHARACTER_Y_CENTER_OFFSET = -8
TILE0_X = (SCREEN_WIDTH - SPRITE_SIZE) // 2
TILE0_Y = SPRITE_SIZE
TILE_X_OFFSET = SPRITE_SIZE // 2
TILE_Y_OFFSET = SPRITE_SIZE // 4

# TILE TYPES
#
TILE_TERRAIN = 'terrain'
TILE_CHARACTER = 'character'
TILE_TYPES = [TILE_TERRAIN, TILE_CHARACTER]

# CHARACTERS
#
CHARACTER_TEST = 'test'
CHARACTER_TYPES = [CHARACTER_TEST]

# ERROR MESSAGES
#
UNKNOWN_TILE_TYPE = 'Requested Tile_Type for TileSet is unknown'
UNKNOWN_CHARACTER_TYPE = 'Requested Character_Type for TileSet is unknown'
UNKNOWN_CAMERA_ORIENTATION = f'Unknown Camera Orientation, assuming {CAMERA_NORTH}'
INCORRECT_COORD_FORMAT = 'Incorrect coord format. Expected : (x, y, z)'
